export const CARDS = 'Tarjetas'.toUpperCase()
export const CLOSE = 'Cerrar'.toUpperCase()
export const EDIT = 'Editar'.toUpperCase()
export const ENTER_DESCRIPTION = 'Ingrese una descripción'
export const ENTER_TITLE = 'Ingrese el título'
export const LOGIN = 'Ingresar'.toUpperCase()
export const SAVE = 'Guardar'.toUpperCase()
export const SELECT_IMAGE = 'Seleccionar imagen'.toUpperCase()
export const SELECT_AUDIO = 'Seleccionar audio'.toUpperCase()
export const SCHEDULE_SAVED = 'Cronograma guardado exitosamente.'
export const CARD_SAVED = 'Tarjeta guardada exitosamente.'
export const SCHEDULE_CARDS_SAVED = 'Tarjetas guardadas exitosamente.'
export const BIRTH_DATE = 'Fecha de nacimiento'.toUpperCase()
export const BIRTH_DATE_INVALID =
  'La fecha de nacimiento es inválida (dd/mm/aaaa).'
export const BIRTH_DATE_PLACEHOLDER = '20/10/1998'
export const BIRTH_DATE_REQUIRED = 'La fecha de nacimiento es requerida.'
export const CONSIDERATIONS = 'Consideraciones'.toUpperCase()
export const CONSIDERATIONS_PLACEHOLDER = 'Algunas consideraciones.'
export const CONSIDERATIONS_REQUIRED = 'Las consideraciones son requeridas.'
export const DATE = 'Fecha'.toUpperCase()
export const DATE_INVALID = 'La fecha es inválida (dd/mm/aaaa).'
export const DATE_REQUIRED = 'La fecha es requerida.'
export const HORSE = 'Caballo'.toUpperCase()
export const HORSE_PLACEHOLDER = 'Tornado'
export const HORSE_REQUIRED = 'El caballo es requerido.'
export const METHODOLOGY = 'Metodología'.toUpperCase()
export const METHODOLOGY_PLACEHOLDER = 'Alguna metodología.'
export const METHODOLOGY_REQUIRED = 'La metodología es requerida.'
export const NAME = 'Nombre'.toUpperCase()
export const NAME_PLACEHOLDER = 'Juan Pérez'
export const NAME_REQUIRED = 'El nombre es requerido.'
export const EQUIPMENT = 'Equipamiento'.toUpperCase()
export const EQUIPMENT_PLACEHOLDER = 'Montura'
export const EQUIPMENT_REQUIRED = 'El equipo es requerido.'
export const ADD_CARDS = 'Agregar Tarjetas'.toUpperCase()
export const SELECT_TEXT = 'Seleccione tarjetas...'.toUpperCase()
export const SELECTED_TEXT = 'Seleccionadas'.toUpperCase()
export const CONFIRM_TEXT = 'Confirmar'
export const SEARCH_PLACEHOLDER_TEXT = 'Buscar'.toUpperCase()
export const TITLE_SCHEDULE = 'Complete los siguientes campos para agregar un cronograma.'
export const TITLE_CARDS = 'Complete los siguientes campos para agregar una tarjeta.'
export const TITLE = 'Título'.toUpperCase()
export const DESCRIPTION = 'Descripción'.toUpperCase()
export const IMAGE = 'Imagen'.toUpperCase()
export const AUDIO = 'Audio'.toUpperCase()
export const SELECT_CARDS = 'Seleccionar tarjetas'.toUpperCase()
